apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dispatch.fullname" . }}
  labels:
{{ include "dispatch.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{ include "dispatch.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "dispatch.labels" . | indent 8 }}
    spec:
      imagePullSecrets:
        - name: harbor
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
