---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "dispatch.fullname" . }}
  labels:
{{ include "dispatch.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
      - {{ .Values.domain }}
      {{- range $domain := .Values.altdomains }}
      - {{ $domain }}
      {{- end }}
    secretName: {{ template "dispatch.fullname" . }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "dispatch.fullname" . }}
              servicePort: 80
{{- $root := . }}
{{- range $domain := .Values.altdomains }}
    - host: {{ $domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "dispatch.fullname" $root }}
              servicePort: 80
    - host: www.{{ $domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "dispatch.fullname" $root }}
              servicePort: 80
{{- end }}