{{- if .Values.mariadb.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ template "dispatch.fullname" . }}-mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
spec:
  selector:
    app: mariadb
{{ include "dispatch.labels.noapp" . | indent 4 }}
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "dispatch.fullname" . }}-
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
{{ include "dispatch.labels.noapp" . | indent 8 }}
    spec:
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ template "dispatch.fullname" . }}-mariadb
      containers:
        - name: mariadb
          imagePullPolicy: Always
          image: mariadb:10
          env:
            - name: MYSQL_USER
              value: {{ .Values.mariadb.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mariadb.password }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mariadb.password }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database }}
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306

{{ end }}