{{- if .Values.mongodb.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:  {{ template "dispatch.fullname" . }}-mongodb
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hardkp
    - nfsvers=4.1
  nfs:
      path: /mnt/nfs/{{ .Release.Name }}-mongodb
      server: 10.244.0.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ template "dispatch.fullname" . }}-mongodb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName:  {{ template "dispatch.fullname" . }}-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  selector:
    app: mongodb
{{ include "dispatch.labels.noapp" . | indent 4 }}
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "dispatch.fullname" . }}-
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
{{ include "dispatch.labels.noapp" . | indent 8 }}
    spec:
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ template "dispatch.fullname" . }}-mongodb
      containers:
        - name: mongodb
          imagePullPolicy: Always
          image: mongo:4-xenial
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.password }}
          volumeMounts:
            - name: datadir
              mountPath: /data/db
          ports:
            - containerPort: 27017

{{ end }}