{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ template "dispatch.fullname" . }}-postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
spec:
  selector:
    app: postgresql
{{ include "dispatch.labels.noapp" . | indent 4 }}
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "dispatch.fullname" . }}-
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
{{ include "dispatch.labels.noapp" . | indent 8 }}
    spec:
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ template "dispatch.fullname" . }}-postgresql
      containers:
        - name: postgresql
          imagePullPolicy: Always
          image: postgres:10
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432

{{ end }}