{{- $root := . }}
{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dispatch.fullname" $root }}-{{ $secret.name }}
type: Opaque
data:
  file: {{ $secret.value }}
{{- end }}