apiVersion: v1
kind: Service
metadata:
  name: {{ template "dispatch.fullname" . }}
  labels:
{{ include "dispatch.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
{{ include "dispatch.labels" . | indent 4 }}